directory: ~/Music            # The default library root directory.
library: ~/Music/library.db   # The default library database file to use.

plugins: convert chroma badfiles bareasc duplicates edit fromfilename fuzzy lyrics missing random info

convert:
    format: flac
