directory: ~/Music            # The default library root directory.
library: ~/Music/library.db   # The default library database file to use.

plugins: convert badfiles bareasc duplicates edit random lyrics fromfilename info missing zero

import:
    copy: no
    move: yes
    languages: en kr jp cn

convert:
    auto: yes
    format: flac
    dest: ~/Music
    delete_originals: true
match:
    strong_rec_thresh: 0.05
    preferred:
        countries: ['US', 'GB|UK']
zero:
    auto: no
