directory: ~/Music            # The default library root directory.
library: ~/Music/library.db   # The default library database file to use.

plugins: convert chroma badfiles bareasc duplicates edit

convert:
    format: flac
match:
    strong_rec_thresh: 0.05
    preferred:
        countries: ['US', 'GB|UK']
